version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: evetools
      POSTGRES_PASSWORD: evetools
      POSTGRES_DB: evetools
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'supertokens_user', '-d', 'supertokens' ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: evetools
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  nats:
    image: nats
    command: ["-js", "-sd", "/nats"]
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats-data:/nats

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql:7.0
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://evetools:evetools@postgres:5432/evetools"
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5




volumes:
  postgres-data:
  mongo-data:
  nats-data: